kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-indicator-controller
subjects:
  - kind: ServiceAccount
    name: prometheus-indicator-controller
    namespace: monitoring-indicator-protocol
roleRef:
  kind: ClusterRole
  name: prometheus-indicator-controller
  apiGroup: rbac.authorization.k8s.io
